export const state = {
  sendCurrency: "USD",
  receiveCurrency: "EUR",
  amount: 0,
  rate: null,
  range: "1M",
  rangeData: {},
  activeTab: "history",
  currencies: {},
  rates: {},
  ratesEUR: {},
  ratesEURYesterday: {},
  favorites: [],
  log: [],
};
